### ISSUE TITLE
Binary installation?

### ISSUE THREAD

**Issue by jlperla** [odow/PATH.jl#1]
Are you intending this to replace https://github.com/chkwon/PATHSolver.jl ?  If so, is there any way to copy the download and installation approach of the path binaries from it (https://github.com/chkwon/PATHSolver.jl/blob/master/deps/build.jl)?  The usability of the package would increase substantially!

**Comment by odow** [comment]
Yes. I'm working with M. Ferris for him to host binaries for us. It's a WIP. In the short-term, you can install GAMS and get the latest version of PATH from there. You just need to put a copy of `libpath50.so` in `/deps`.

**Comment by jlperla** [comment]
Great.  Once you get things up and running with the binaries, hopefully a few of uscan help with testing prior to moving off of PATHSolver.jl

**Comment by arnavs** [comment]
@odow Could you link to this issue in the install section of the docs? Would make things much clearer, since the PATH website has a bunch of different interfaces/download options.

**Comment by odow** [comment]
@arnavs please make a pull request. The versions on the PATH website are out-of-date. You need the latest `libpath50` that is included in the latest GAMS release.

**Comment by chkwon** [comment]
@odow I was wondering any update on this plan to host binary files.

**Comment by odow** [comment]
I'll talk to Michael again.

**Comment by weibezahn** [comment]
Just a note for Windows users (sorry...): you can find the PATH library in the main folder of your GAMS installation as `path50.dll`

**Comment by jlperla** [comment]
Hi @odow  I was curious if things have moved forward at all for binary hosting.  I fear the the spectacular wrapper from @chkwon  is nearing the end of its life (I am not sure if it works with Juila 1.4?  Or possibly my upgrade broke stuff in an unrelated way).

BTW, I see stuff about the GAMS installation, but I am not sure this is something I would ever install unless it is automatic?

**Comment by odow** [comment]
I am still talking to Michael. Mail me privately, `<first>.<last>@northwestern.edu` and I will send you a work-around.

**Comment by jlperla** [comment]
@odow  Thanks so much, I will reach out if I need a workaround.  My main concern is not me (I forked the PATHSolver.jl in order to patch up Juila 1.3+ support and submitted a PR to that repo) but rather that I want other people to be able to easily use the code in my the repository associated with my paper.  Most economists don't julia (and very few have GAMS installed) so if setup is difficult, they won't bother playing with the code.  These LCPs have a major application in solving optimal stopping problems in macroeconomics.

That said, I don't want to open things up for a few months.

**Comment by odow** [comment]
The work-around is just an environment variable to set to where I have some cached binaries:
https://github.com/odow/PATH.jl/blob/eb1201fb7c62f87ce3e0ca279e17994982070cce/deps/build.jl#L12

Hopefully, by the time your paper is out, we will have automated binary installation.

**Comment by chkwon** [comment]
@odow Just curious. Is there any reason you're not using binaries from https://github.com/ampl/pathlib? Perhaps because it is not maintained and not the most latest version?

**Comment by odow** [comment]
Yeah, the C API wraps version 5.0. Michael is in the process of tidying the binaries to release via his UW site
