### ISSUE TITLE
Register PATH

### ISSUE THREAD

**Issue by odow** [odow/PATH.jl#14]
- [ ] Add to General registry https://github.com/JuliaRegistries/General/pull/28646
- [ ] Wait for a tag
- [ ] Update README with new install instructions

**Comment by odow** [comment]
@chkwon, the other option is for me to make a PR to replace PATHSolver with this code. Are you planning on making future releases of PATHSolver?

**Comment by chkwon** [comment]
If you think it is an easier option, I think it is a good idea.  I don't plan to make any future releases, given you will register PATH. There is no point of doing so.

**Comment by odow** [comment]
PR is here: https://github.com/chkwon/PATHSolver.jl/pull/44.

Once merged I will archive this repository and point people toward PATHSolver.jl.

**Comment by odow** [comment]
Closing. PATH.jl has been released as PATHSolver.jl v1.0.
